2024-09-10 17:07:08,712 INFO    StreamThr :527582 [internal.py:wandb_internal():85] W&B internal server running at pid: 527582, started at: 2024-09-10 17:07:08.711660
2024-09-10 17:07:08,713 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: status
2024-09-10 17:07:08,714 INFO    WriterThread:527582 [datastore.py:open_for_write():87] open: /home/ubuntu/frontend/bistro/wandb/run-20240910_170708-Miner-5GQw7/run-Miner-5GQw7.wandb
2024-09-10 17:07:08,715 DEBUG   SenderThread:527582 [sender.py:send():391] send: header
2024-09-10 17:07:08,718 DEBUG   SenderThread:527582 [sender.py:send():391] send: run
2024-09-10 17:07:08,722 INFO    SenderThread:527582 [sender.py:_setup_resume():761] checking resume status for None/bistro/Miner-5GQw7
2024-09-10 17:07:08,829 ERROR   SenderThread:527582 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:08,829 ERROR   SenderThread:527582 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:10,056 ERROR   SenderThread:527582 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:10,056 ERROR   SenderThread:527582 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:12,156 ERROR   SenderThread:527582 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:12,157 ERROR   SenderThread:527582 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:12,157 INFO    SenderThread:527582 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/ubuntu/frontend/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-09-10 17:07:13,720 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:16,326 ERROR   SenderThread:527582 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:16,326 ERROR   SenderThread:527582 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:18,721 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:23,723 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:25,595 ERROR   SenderThread:527582 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:25,595 ERROR   SenderThread:527582 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:28,725 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:33,726 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:38,728 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:43,729 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:44,371 ERROR   SenderThread:527582 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:07:44,371 ERROR   SenderThread:527582 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:07:48,731 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:53,733 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:07:58,736 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:03,737 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:08,739 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:13,740 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:18,742 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:18,809 ERROR   SenderThread:527582 [internal_api.py:execute():349] 409 response executing GraphQL.
2024-09-10 17:08:18,809 ERROR   SenderThread:527582 [internal_api.py:execute():350] {"errors":[{"message":"run Miner-5GQw7 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-09-10 17:08:23,744 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
2024-09-10 17:08:28,745 DEBUG   HandlerThread:527582 [handler.py:handle_request():158] handle_request: keepalive
